### ISSUE TITLE
Service link in activity log leads to stack trace

### ISSUE THREAD

**Issue by log1-c** [Icinga/icingaweb2-module-director#1377]
## Expected Behavior

If you choose an action in the activity log, where a service object has been changed and click the "service-name" link in the diff view it should open the corresponding service.

## Current Behavior

Currently (at least with my setups) I get only a stack trace when clicking on the service name.
![image](https://user-images.githubusercontent.com/24474580/35554312-8a4708f0-059b-11e8-8262-6aef6cc498d3.png)

## Steps to Reproduce (for bugs)

1. Go to activiy log
2. Choose an entry where a service object (not a template) got changed
3. In the "Diff" panel click on the link for the service name

## Your Environment

* Director version (System - About): 1.4.2 + 1.4.3
* Icinga Web 2 version and modules (System - About): 2.4.2 + 2.5.0 + 2.5.1
* Icinga 2 version (`icinga2 --version`): 2.8.0 + 2.8.1
* Operating System and version: Ubuntu 14.04 LTS + 16.04 LTS

System with Ubuntu 14.04 has:
Icinga2 2.8.1, IcingaWeb2 2.4.2 and Director 1.4.2
System with Ubuntu 16.04 has:
Icinga2 2.8.0, IcingaWeb2 2.5.0 and Director 1.4.2
Test-System with Ubuntu 16.04 has:
Icinga2 2.8.1, IcingaWeb2 2.5.1 and Director 1.4.3

**Comment by dbu1986** [comment]
Same here:
### Your Environment
- Director version (System - About): 1.5.1
- Icinga Web 2 version and modules (System - About): 2.6.1
- Icinga 2 version (icinga2 --version): 2.9.1
- Operating System and version: RHEL 7.5


Adding the GET parameter "host" in the link to the service should fix it:
``` /icingaweb2/director/service?name=[SERVICENAME]&host=[HOSTNAME]```


Another tiny bug occurs at **servicesets** (please notify me if you want me to open a separate issue for this):
Buggy URL:
``` /icingaweb2/director/service_set?name=[SERVICESETNAME]```
Fixed URL:
``` /icingaweb2/director/serviceset?name=[SERVICESETNAME]```

**Comment by log1-c** [comment]
@lazyfrosch 
Just stumbled upon the problem again.
This problem still exists for applied servcies
![image](https://user-images.githubusercontent.com/24474580/86753729-99438380-c040-11ea-933e-aadeb8225a5b.png)

For service sets there is no stack trace anymore
